const products = [
  ['armacao-pronta','Armação Pronta'],['bloco-sextavado','Bloco Sextavado'],['concregrama','Concregrama'],['guias-de-concreto','Guias de Concreto'],['lajota-solar','Lajota Solar'],['laje-painel-trelicado','Laje Painel Treliçado'],['piso-tatil','Piso Tátil'],['baldrame-pronto','Baldrame Pronto'],['blocos-de-concreto','Blocos de Concreto'],['cortina-de-contencao','Cortina de Contenção'],['isopor-para-enchimento','Isopor para Enchimento'],['mouroes-de-concreto','Mourões de Concreto'],['paver-piso-intertravado','Paver — Piso Intertravado'],['piso-antiderrapante','Piso Antiderrapante'],['sopac','Sopac'],['barreira-new-jersey','Barreira New Jersey'],['brises-e-pergolado','Brises e Pergolado'],['elemento-vazado-cobogo','Elemento Vazado Cobogó'],['jardim-vertical','Jardim Vertical'],['mureta-canal-de-santos','Mureta / Canal de Santos'],['pilar-para-garagem','Pilar para Garagem'],['piso-drenante','Piso Drenante'],['tampa-poco-de-visitas','Tampa para Poço de Visitas'],['bate-rodas-e-prisma','Bate Rodas e Prisma'],['caixas-de-passagem','Caixas de Passagem'],['grelhas-de-concreto','Grelhas de Concreto'],['laje-trelicada','Laje Treliçada'],['muro-pre-moldado','Muro Pré-Moldado'],['pingadeira','Pingadeira / Capa de Muro'],['pisos-para-calcada','Pisos para Calçada'],['vergas','Vergas']
];
const productGrid = document.querySelector('[data-product-grid]');
if (productGrid) productGrid.innerHTML = products.map(([slug,name]) => `<a class="product-link" href="produto.html?produto=${slug}">${name}<br><small>Ver detalhes →</small></a>`).join('');
const productDetail = document.querySelector('[data-product-detail]');
if (productDetail) { const slug = new URLSearchParams(location.search).get('produto'); const product = products.find(item => item[0] === slug) || products[0]; document.title = `${product[1]} | Moldelaje`; productDetail.innerHTML = `<section class="page-hero"><span class="eyebrow">Produtos Moldelaje</span><h1>${product[1]}</h1><p>Pré-moldado de concreto produzido com qualidade, segurança e atendimento para toda a Baixada Santista.</p></section><main class="page-content two-col"><div><h2>${product[1]}</h2><p>Uma solução Moldelaje para obras residenciais, comerciais e urbanas. Desenvolvida para entregar resistência, praticidade e bom acabamento.</p><p>Fale com nossa equipe para receber orientação técnica, disponibilidade e um orçamento conforme a necessidade da sua obra.</p><a class="btn-primary" href="contato.html">Solicitar orçamento</a></div><aside class="info-panel"><h3>Precisa de ajuda?</h3><p>Conte o que você precisa e nossa equipe indicará a melhor solução.</p><a href="https://wa.me/551334673300" target="_blank" rel="noopener">WhatsApp: (13) 3467-3300</a></aside></main>`; }
const indexProductSlugs = {'Laje Treliçada':'laje-trelicada','Painel Treliçado':'laje-painel-trelicado','Blocos de Concreto':'blocos-de-concreto','Paver Intertravado':'paver-piso-intertravado','Muro Pré-Moldado':'muro-pre-moldado','Piso Drenante':'piso-drenante','Elemento Vazado (Cobogó)':'elemento-vazado-cobogo','Guias de Concreto':'guias-de-concreto','Mourões de Concreto':'mouroes-de-concreto','Barreira New Jersey':'barreira-new-jersey','Grelhas de Concreto':'grelhas-de-concreto','Piso Tátil':'piso-tatil'};
document.querySelectorAll('.produto-card').forEach(card => { const title = card.querySelector('h3')?.textContent.trim(); const slug = indexProductSlugs[title]; if (slug) card.href = `produto.html?produto=${slug}`; });
